### ISSUE TITLE
Update wiki pages to current spec and implementation

### ISSUE THREAD

**Issue by roeslpa** [Qabel/qabel.github.io#120]
Several wiki pages do not reflect the current state of Qabel.

**Comment by roeslpa** [comment]
Hi @Qabel/developer,
before I update the documentation with my ideas, I would like to have an ack regarding a little structure update: the documentation was growing with all new ideas and requirements which resulted in a (from my point of view) unstructured collection of specs, requirements and plans. Best example: there are three section on drop, 1. abstract description of plans, requirements and goals (okay), 2. detailed description of drop protocol on the client (do not know whether up to date), 3. detailed description of the remaining drop protocol. Thus I would propose the following structure:

+ Intro
  * Abstract	(okay, but to be updated)
  * Introduction	(okay, but to be updated)
  * Architectural Overview	(to be updated)
+ Components
  * Drop	(seems to be up to date)
  * Box	(up to date)
  * Contacts	(to be split: here only brief description)
  * Modules	(to be enhanced: more about platform)
  * Crypto	(up to date)
+ Client Data
  * Local Settings	(parts or current configuration)
  * Synced Account Information	(parts or current configuration + parts of contact data - drop message stuff)
+ Communication Protocols
  * Drop Protocols	(merge with current client data drop + proof of work)
  * Box Protocol	(up to date)
  * Contacting and Accounting	(to be created about registration and contacting stuff)
  * Threat Model	(to be reviewed)
+ Wording
  * Appendix Glossary	(up to date)

What do you think?

**Comment by thechauffeur** [comment]
We will further work on some topics like proof-of-work and drop in the near future and should update the spec (content and structure) immediately afterwards.

**Comment by roeslpa** [comment]
I would propose to approach like this:

1. Update generic pages (like intro)
1. Remove outdated info
1. Create a better structure
1. Add current undocumented information

**Comment by roeslpa** [comment]
Regarding **Drop Spec** (discussed with @thechauffeur, @schulze, @cburkert, @audax) :

* http://qabel.github.io/docs/Qabel-Protocol-Drop/ is implemented as specified
* everything below http://qabel.github.io/docs/Qabel-Client-Drop/#encryption except the history paragraph is implemented as specified; everything above is not implemented or used
* further information might be requested from @L-Henke 

=> Not implemented spec will be marked as such

**Comment by hartmannaf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

bisher bin ich seit letzte Woche Donnerstag bis diese Woche Freitag
krankgeschrieben, werde dann am Montag wieder schauen wie es mir geht
und mich dann nochmal melden.

Mit freundlichen Grüßen
Alexander Hartmann

Am 12.01.2016 um 16:03 schrieb roeslpa:
> Regarding **Drop Spec** (discussed with @thechauffeur, @schulze,
> @cburkert, @audax) :
> 
> * http://qabel.github.io/docs/Qabel-Protocol-Drop/ is implemented
> as specified * everything below
> http://qabel.github.io/docs/Qabel-Client-Drop/#encryption except
> the history paragraph is implemented as specified; everything above
> is not implemented or used * further information might be requested
> from @L-Henke
> 
> => Not implemented spec will be marked as such
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/Qabel/qabel.github.io/issues/120#issuecomment-17094
0476
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBAgAGBQJWlTWjAAoJENE7AKGG2wVdnZ8P/2ebLIoQELWQcGlomQCevAo2
4EK70+5EtezcYeHVlJML001kAyAAtOLjS/PJiiemATx7jzsw4YUtL+isjXHdXF/u
OqWmlI/dWgoUbV5e7ckQ/iiWTCJ9AzRwf2zFLQIpIvgVhtX99lNPnO9bzIbuaSYB
5QtSOhNFV6sZo/l5dKvgBXSwqKBdeiWVp5k65hf9dEmNYW5g1Y7WrIpR9Mi2CM1i
rm9blpvtiDSpCvvx21uYHj+NuzJ9HzF/2LRQgavR1mSHdAsrOG2Jkw9oZqIzsokd
/pUBB6P/ij9EWxt+3JZr1rgQgqfg7p4ZiZ/UVxYV/l/C2oyLAZlShobEaubOiStL
M2pKzriGytFJOLqgqMY/031K/9f2zicsskBuvESYm2NiANVBy3FNSjy66e5MMRjj
LG6W0Q5J37LBQbxZUANX0MoZnZIp7sqyHMHcF6mknLgGHo+sJYo258m/sL0/SJTa
BnVV0b/naveJW9npknwAcJFukvvdQcR430CYPgGLYsZ6VWiivEps847q3gcPQ+8g
Nb4GLsH7LLpK0uF7xPMJrsT8FEqwxEO0SKaZDWPpouMwwp0v1Q1W95k1fVqxry01
lUMhAuM72rmXJNl6n62G5oulpiYXOna5dYCXMpb5v/8SU+9gbQI/Biah8GIQuwur
3dlIRuED9yy7C7gL0REm
=+3Yv
-----END PGP SIGNATURE-----
