### ISSUE TITLE
Define type formats

### ISSUE THREAD

**Issue by roeslpa** [Qabel/qabel.github.io#138]
Define format of keys for exporting/uploading... @jmt85 @L-Henke

**Comment by roeslpa** [comment]
Just to start the discussion: any other thoughts?

| Data type | Definition |
| --- | --- |
| Int | 32-bit signed two's complement integer |
| Long | 64-bit signed two's complement integer |
| String | UTF-8 encoded |
| Keyformat | Base46-RFC 4648 encoded UTF-8 String |

**Comment by audax** [comment]
| Data type | Definition |
| --- | --- |
| Int | 32-bit signed two's complement integer  |
| Long | 64-bit signed two's complement integer |
| String | UTF-8 encoded and (if applicable) null terminated|
| Keyformat | Hex-String with ASCII encoding. Every byte of data is converted into the corresponding 2-digit hex representation. The returned bytes object is therefore twice as long as the length of data.|
