### ISSUE TITLE
Remove used prefix from exported identity

### ISSUE THREAD

**Issue by roeslpa** [Qabel/qabel.github.io#159]
Since several issues occur when attaching (account related info like) the prefix to the identity it was proposed to remove it. Instead the used prefix can easily be found by:
1. Get the prefixes of the used account
2. The prefix in which the name of one meta file = Hash(prefix||privKey) is the used prefix of the identity
3. If such a prefix does not exist: create a new prefix

Any comments?

**Comment by audax** [comment]
Resolved by https://github.com/Qabel/qabel-core/pull/631
The prefix in the identity is now just a preference and a fallback to other prefixes of the account is implemented.

**Comment by julianseeger** [comment]
FTR.: the algorithm proposed by @roeslpa is contained:

* *prefer main prefix (prefix known by the local identity, that is assign to the current account)*
* *use first prefix that exists locally and remote and has an index / root*
* **use first prefix that exists remote and has an index / root**
* *use first prefix that exists locally and remote (and has no index / root => create index)*
* *create new prefix (and index)*

If we take the default exception- and misuesfree usecase, the first two options take the same account. The "main prefix" should have been chosen by exactly that algorithm and if the identity is not broken, the second option will either contain that prefix or none (and thus default to the first one from the server containing the (index) meta file.

While looking at this, the forth option sounds like it could become problematic and could lead to prefixes used multiple times ... and break as soon as some FSCK is implemented ... we should check that pre https://github.com/Qabel/qabel-core/issues/636
