### ISSUE TITLE
Choosing drop id - meta data

### ISSUE THREAD

**Issue by f-porter** [Qabel/qabel.github.io#16]
How will the client choose the drop id?
And how do we ensure that the drops of qabel users will overlap in order to obfuscate meta data?

**Comment by thechauffeur** [comment]
Well we have to decide this until the first BETA test. @cburkert you proposed a simple solution for this problem. Please write something here :)

**Comment by cburkert** [comment]
My proposal is described in https://github.com/Qabel/qabel.github.io/issues/16#issuecomment-52052136 and is already implemented in Qabel/qabel-core#281 - nothing more to say.

I think this approach is sufficient for the beta.

**Comment by thechauffeur** [comment]
@cburkert OK I see. Should this be in the documentation?

**Comment by roeslpa** [comment]
@cburkert are you okay with it if I add it to the documentation?

**Comment by cburkert** [comment]
I am. Go ahead.
