### ISSUE TITLE
Module Manager documentation

### ISSUE THREAD

**Issue by f-porter** [Qabel/qabel.github.io#41]
You have already specified some stuff for the module manager, haven't you?
Maybe you could add that to the documentation?

**Comment by thechauffeur** [comment]
Please update the state of this issue @Gottox

**Comment by thechauffeur** [comment]
This is delayed until ackack is used in Qabel.

**Comment by thechauffeur** [comment]
ackack is used in Qabel now.

**Comment by thechauffeur** [comment]
A good showcase would be to have a working qabel-desktop + qabel-helloworld setup.

**Comment by thechauffeur** [comment]
@L-Henke and @schulze and everyone else from @Qabel/developer who knows the ModuleManager. Please have a look at this :)

**Comment by thechauffeur** [comment]
This issue is merely about reading the Javadoc and decide if it is enough together with an example. We do **not** need additional documentation in our documentation repository.

**Comment by thechauffeur** [comment]
I will do this and close this issue if it looks good.

**Comment by thechauffeur** [comment]
This issue is deprecated.
