### ISSUE TITLE
Create separate doc for a detailed threat model

### ISSUE THREAD

**Issue by schulze** [Qabel/qabel.github.io#49]
I would like to create a new wiki page for a threat model.

The page should give detailed information about what information is accessible to the different parties in a Qabel system, e.g. user's client, ISP,  drop server, other user's client, ...

Would everybody be OK with having this as part of this wiki, or should I start such a document somewhere else? Or did anybody already start a threat model somewhere else?

**Comment by thechauffeur** [comment]
Bump.

**Comment by schulze** [comment]
Here is a [link](https://github.com/Qabel/qabel.github.io/blob/master/_docs/Threat-Model.md) to the new location of the document.

**Comment by thechauffeur** [comment]
@schulze is this page still up to date?

**Comment by schulze** [comment]
The page is not up to date, is unfinished and needs work.

**Comment by roeslpa** [comment]
@schulze do you mind if I update the threat model?

**Comment by schulze** [comment]
Just go ahead!

One suggestion: The content I originally had in mind shouldn't really be called a "threat model", but rather a "security policy". I you want to feel free to split or rename the page.
