### ISSUE TITLE
Idea to complicate Drop Server traffic faking

### ISSUE THREAD

**Issue by cburkert** [Qabel/qabel.github.io#58]
As you probably know, the anonymity communication via drop server is essentially based on collisions and therefore on a certain level of server utilization.
But a client cannot know for sure, how much traffic there is on the used drop server.
A client can only check how many foreign drop messages there are in each drop.
But he cannot verify if these foreign messages are uploaded by multiple other real users like himself or if all foreign messages are faked by a single malicious entity (e.g. the server itself) in order to make the client wrongly belief, that he is anonymous and untraceable.

I had the idea to use proof-of-work technique to make drop message faking expansive and un-practicable.
Check out [my suggestion](http://qabel.github.io/docs/Components-Drop/#uncertain-degree-of-anonymity) (second paragraph).

Feedback appreciated.

**Comment by roeslpa** [comment]
This issue was closed by #130
