### ISSUE TITLE
Qabel Browse Page

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel.github.io#67]
The Qabel browse protocol is not yet specified but it is listed on the TOC. Since [the page](https://github.com/Qabel/qabel-doc/wiki/Qabel-Protocol-Browse) is also old we should change that or write something about this in the page.

E.g. the link to an [example](http://qabel.me/chrzuck#ab4c2x2yz3) ist not working.

FYI, **the** browse protocol will not be included in the beta anyway but some sort of getting in contact with each other is still needed.

**Comment by thechauffeur** [comment]
Some sort of key exchange -- at least viable for companies -- must be specified.

**Comment by schulze** [comment]
Working link to the page in question: http://qabel.github.io/docs/Qabel-Protocol-Browse/

**Comment by schulze** [comment]
@thechauffeur Can you please create a qabel-browse-module repository, so I can move the documentation about the browse module there?

We won't work on the browse module in the near future and what we have need not be part of the core documentation.

**Comment by thechauffeur** [comment]
@schulze Done: https://github.com/Qabel/qabel-browse
