### ISSUE TITLE
Use this documentation page only for documenting protocols and such

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel.github.io#83]
not for documenting implementation specific things which depend on things like used technologies (e.g. programming languages or operating systems).

Look at the documentation page for things like this and move them into our Javadoc in the corresponding code repositories (that is [qabel-core](https://github.com/Qabel/qabel-core)).

@jan-schreib, @jasinai and myself will work on this.

**Comment by thechauffeur** [comment]
See Qabel/qabel-core#287.

**Comment by thechauffeur** [comment]
Bump.

**Comment by cburkert** [comment]
Closed by #93
