### ISSUE TITLE
Remove politics from the documentation

### ISSUE THREAD

**Issue by schulze** [Qabel/qabel.github.io#84]
The abstract https://github.com/Qabel/qabel-doc/wiki/Abstract and the preamble https://github.com/Qabel/qabel-doc/wiki/Preamble were added so there is some introduction to the documentation. The preamble is mostly about politics and should be removed; the remaining content can be incorporated into the abstract.

**Comment by schulze** [comment]
Dpends on #85

**Comment by jasinai** [comment]
If you have something in mind, you can open a PR. #85 is done.
