### ISSUE TITLE
Implement review process for changes in the documentation

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel.github.io#85]
The wiki was good enough for producing content in a collaborative way. Now we have content and need less and smaller changes (regarding lines of text) but a review process for those changes. Sadly the GitHub wikis do not work with pull requests.

Therefore we move the wiki pages to the `qabel-doc` repository to be able to apply a pull request + review + merge policy.

* Convert all wiki links to relative links prior migrating the pages (files).
* *Optional*: Change history of `qabel-doc.wiki` (local clone) to let it look like the files have always been in a sub-folder. Do **not** force push -- just do it locally.
* Migrate the wiki pages (files) while keeping the history of (local) `qabel-doc.wiki` via `git merge` into `qabel-doc`.
* Update Home.md in the wiki to refer to the new place of the documentation.
* Use `git rm` to remove all files in `qabel-doc.wiki` except Home.md
* Review push access to the `qabel-doc` repository

If you have better ideas let us know it!

**Comment by thechauffeur** [comment]
We would also need to change links in our Javadoc (we have links to some wiki page in some Java files).

**Comment by thechauffeur** [comment]
@jan-schreib we talked about researching this topic a bit more. Maybe there is a better option than losing the wiki completely etc. (maybe web hooks?).

**Comment by jasinai** [comment]
I recommend Github Pages

**Comment by thechauffeur** [comment]
We will use GitHub pages.

* [ ] Create such a repo from the original doc repo / wiki.
* [ ] Update the old places to reference to the new ones.

**Comment by jasinai** [comment]
The documentation is online. For now it is here: https://jasinai.github.io

**Comment by thechauffeur** [comment]
N1.

* [ ] The documentation page should be the starting page.
* [ ] It is "source code" not "sourcecode".
* [ ] Some pictures break the page.
* [ ] Create qabel github.io repository.
* [ ] We have to link to the new documentation page and not update the old one anymore.

**Comment by thechauffeur** [comment]
* [ ] Add labels.
* [ ] Add milestones.
* [ ] Somehow show pages which are not linked in the new TOC (yaml). E.g. Create a "pages" link which lists *all* documentation pages with their filename.
* [ ] Remove the old TOC page (md).

**Comment by thechauffeur** [comment]
* [ ] Remove the old sidebar (md).
* [ ] Update the main page at https://qabel.github.io accordingly.

**Comment by thechauffeur** [comment]
The documentation has been migrated.

The qabel-doc repo has been renamed to qabel.github.io. That means GitHub provides a redirect from https://github.com/Qabel/qabel-doc/foo/bar to https://github.com/Qabel/qabel.github.io/foo/bar

This is also true for the wiki and it means we don't need to update anything. Issues, milestones, labels, pull requests, internal links, internal links with fully qualified URL, external links to GitHub etc. Everything should just work.

@Qabel/ackack-developer please open new issues if you find problems. Please create pull requests for the documentation now. Use the this repository.
