### ISSUE TITLE
Integrated Noise into documentation

### ISSUE THREAD

**Issue by L-Henke** [Qabel/qabel.github.io#86]
Since #85 isn't done yet, I'll present the changes on the documentation in this issue. This is currently: https://github.com/L-Henke/qabel-doc/commit/28b976cba9a9a51656164098b6b464f4517adbb0

**Comment by jasinai** [comment]
#85 is done, so you can open a PR with your changes.

**Comment by thechauffeur** [comment]
Bump.

**Comment by L-Henke** [comment]
Why did you assign this to me? What do you want me to do? A pull request is opened and referenced.

**Comment by thechauffeur** [comment]
@schulze, @cburkert please review the PR.

**Comment by thechauffeur** [comment]
And others to test if you can understand this :)
